const matchTableActionTypes = {
	LOAD_TMP_STATE: 'LOAD_TMP_STATE',
	ADD_PLAYER: 'ADD_PLAYER',
	CHANGE_TMP_PLAYER_NAME: 'CHANGE_TMP_PLAYER_NAME',
	CHANGE_LEFT_PLAYER_POINT: 'CHANGE_LEFT_PLAYER_POINT',
	CHANGE_RIGHT_PLAYER_POINT: 'CHANGE_RIGHT_PLAYER_POINT',
	CALC_TOTAL_RESULTS: 'CALC_TOTAL_RESULTS',
}

export default matchTableActionTypes;