const matchTableActionTypes = {
	ADD_PLAYER: 'ADD_PLAYER',
	CHANGE_TMP_PLAYER_NAME: 'CHANGE_TMP_PLAYER_NAME',
	CHANGE_LEFT_PLAYER_POINT: 'CHANGE_LEFT_PLAYER_POINT',
	CHANGE_RIGHT_PLAYER_POINT: 'CHANGE_RIGHT_PLAYER_POINT',
}

export default matchTableActionTypes;